/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.uepb.bsc7.www.UI;

import com.br.uepb.bsc7.www.persistence.InventarioDAO;
import com.br.uepb.bsc7.www.persistence.TabelaRelatorio;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author Coordenação
 */
public class InventarioUI extends javax.swing.JFrame {

    JFileChooser fc = new JFileChooser();
    //Observacoes objObs = new Observacoes();
    //String nomeArq = null;
    private boolean primChamada;
    InventarioDAO dao = new InventarioDAO();
    ResultSet rs = null;
    ResultSetMetaData metadados = null;
    ArrayList<String> dadosIns = new ArrayList<>();
    //TableModel modeloTabelaLocaliz;
    //TableModel modeloTabelaTombo;
    TableModel modeloTabelaAcerv;
    TableModel modeloTabelaUlt;
    //public static boolean emExecucao = false;
    private boolean logado = false;
    private String obsIns = "";
    
    /**
     * Creates new form InventarioUI
     */
    public InventarioUI() {
        primChamada = true;
        initComponents();
        setFocusUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoAbas = new javax.swing.JTabbedPane();
        abaInicio = new javax.swing.JPanel();
        painelLogin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        userBD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pswdBD = new javax.swing.JPasswordField();
        botOk = new javax.swing.JButton();
        sesaoIni = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabUltIni = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        abaAcervo = new javax.swing.JPanel();
        painelCargArqAcervo = new javax.swing.JPanel();
        botCargAcervo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botSelAcervo = new javax.swing.JButton();
        endArqAcervo = new javax.swing.JTextField();
        painelLeCodAcervo = new javax.swing.JPanel();
        codBar = new javax.swing.JTextField();
        vrfExemplar = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabUltCod = new javax.swing.JTable();
        botInsCod = new javax.swing.JButton();
        botLimpCod = new javax.swing.JButton();
        botDesfInsCod = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abaSIABI = new javax.swing.JPanel();
        painelCargArqSIABI = new javax.swing.JPanel();
        botCargSIABI = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botSelSIABI = new javax.swing.JButton();
        endArqSIABI = new javax.swing.JTextField();
        abaRelatorios = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        botGerRelat = new javax.swing.JButton();
        comboRelat = new javax.swing.JComboBox<>();
        abaAjuda = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(927, 360));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        grupoAbas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grupoAbas.setPreferredSize(new java.awt.Dimension(699, 200));
        grupoAbas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                grupoAbasStateChanged(evt);
            }
        });
        grupoAbas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                grupoAbasFocusGained(evt);
            }
        });

        abaInicio.setPreferredSize(new java.awt.Dimension(694, 200));
        abaInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                abaInicioFocusGained(evt);
            }
        });

        painelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel7.setText("Usuário:");

        userBD.setPreferredSize(new java.awt.Dimension(150, 22));
        userBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBDActionPerformed(evt);
            }
        });
        userBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userBDKeyPressed(evt);
            }
        });

        jLabel8.setText("Senha:");

        pswdBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdBDActionPerformed(evt);
            }
        });
        pswdBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswdBDKeyPressed(evt);
            }
        });

        botOk.setText("Ok");
        botOk.setMnemonic(KeyEvent.VK_O);
        botOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botOkActionPerformed(evt);
            }
        });

        sesaoIni.setText("Sessão iniciada!");
        sesaoIni.setVisible(false);

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswdBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                        .addComponent(botOk)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                        .addComponent(sesaoIni)
                        .addGap(45, 45, 45))))
        );

        painelLoginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pswdBD, userBD});

        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(userBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pswdBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sesaoIni)
                .addContainerGap())
        );

        painelLoginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pswdBD, userBD});

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Últimos valores inseridos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 153))); // NOI18N

        tabUltIni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Tombo", "Localização (CDD)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabUltIni);

        jLabel9.setText("Penúltimo:");

        jLabel10.setText("Último:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );

        javax.swing.GroupLayout abaInicioLayout = new javax.swing.GroupLayout(abaInicio);
        abaInicio.setLayout(abaInicioLayout);
        abaInicioLayout.setHorizontalGroup(
            abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        abaInicioLayout.setVerticalGroup(
            abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Início", abaInicio);

        abaAcervo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                abaAcervoFocusGained(evt);
            }
        });

        painelCargArqAcervo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carregar arquivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelCargArqAcervo.setToolTipText("Selecione um arquivo de texto simples (TXT) ou do Excel (XLS)");
        painelCargArqAcervo.setPreferredSize(new java.awt.Dimension(221, 210));

        botCargAcervo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_bd.png"))); // NOI18N
        botCargAcervo.setMnemonic(KeyEvent.VK_C);
        botCargAcervo.setText("Carregar arquivo");
        botCargAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCargAcervoActionPerformed(evt);
            }
        });

        jLabel3.setText("1º Passo:");

        jLabel4.setText("2º Passo:");

        botSelAcervo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_open.png"))); // NOI18N
        botSelAcervo.setMnemonic(KeyEvent.VK_S);
        botSelAcervo.setText("Selecionar arquivo");
        botSelAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSelAcervoActionPerformed(evt);
            }
        });

        endArqAcervo.setForeground(new java.awt.Color(204, 204, 204));
        endArqAcervo.setText("Nenhum arquivo selecionado");
        endArqAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endArqAcervoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCargArqAcervoLayout = new javax.swing.GroupLayout(painelCargArqAcervo);
        painelCargArqAcervo.setLayout(painelCargArqAcervoLayout);
        painelCargArqAcervoLayout.setHorizontalGroup(
            painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCargArqAcervoLayout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addGap(12, 12, 12))
            .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                .addGroup(painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botSelAcervo)
                            .addComponent(endArqAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botCargAcervo))
                            .addComponent(jLabel4))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        painelCargArqAcervoLayout.setVerticalGroup(
            painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endArqAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botSelAcervo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botCargAcervo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelLeCodAcervo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Leitura de Código de Barras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelLeCodAcervo.setPreferredSize(new java.awt.Dimension(434, 210));

        codBar.setCaretPosition(0);
        codBar.setToolTipText("");
        codBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codBarActionPerformed(evt);
            }
        });
        codBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codBarKeyPressed(evt);
            }
        });

        vrfExemplar.setText("Verificar depois");
        vrfExemplar.setMnemonic(KeyEvent.VK_F);
        vrfExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrfExemplarActionPerformed(evt);
            }
        });

        tabUltCod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tombo", "Verificar", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabUltCod.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabUltCod);
        if (tabUltCod.getColumnModel().getColumnCount() > 0) {
            tabUltCod.getColumnModel().getColumn(1).setMinWidth(100);
            tabUltCod.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabUltCod.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        botInsCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_plus.png"))); // NOI18N
        botInsCod.setText("Inserir");
        botInsCod.setToolTipText("Insere o valor acima na tabela");
        botInsCod.setMnemonic(KeyEvent.VK_I);
        botInsCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInsCodActionPerformed(evt);
            }
        });
        botInsCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botInsCodKeyPressed(evt);
            }
        });

        botLimpCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_limpar.png"))); // NOI18N
        botLimpCod.setText("Limpar");
        botLimpCod.setToolTipText("Limpa os dados do campo acima");
        botLimpCod.setMnemonic(KeyEvent.VK_L);
        botLimpCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpCodActionPerformed(evt);
            }
        });

        botDesfInsCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_desfazer.png"))); // NOI18N
        botDesfInsCod.setText("Desfazer");
        botDesfInsCod.setToolTipText("Desfaz a última inserção de dado na tabela");
        botDesfInsCod.setMnemonic(KeyEvent.VK_D);
        botDesfInsCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDesfInsCodActionPerformed(evt);
            }
        });

        jLabel1.setText("Últimos códigos lidos");

        jLabel2.setText("Código");

        javax.swing.GroupLayout painelLeCodAcervoLayout = new javax.swing.GroupLayout(painelLeCodAcervo);
        painelLeCodAcervo.setLayout(painelLeCodAcervoLayout);
        painelLeCodAcervoLayout.setHorizontalGroup(
            painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLeCodAcervoLayout.createSequentialGroup()
                        .addComponent(codBar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vrfExemplar))
                    .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                        .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                                .addComponent(botInsCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botLimpCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botDesfInsCod))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLeCodAcervoLayout.setVerticalGroup(
            painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLeCodAcervoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vrfExemplar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botInsCod)
                    .addComponent(botLimpCod)
                    .addComponent(botDesfInsCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout abaAcervoLayout = new javax.swing.GroupLayout(abaAcervo);
        abaAcervo.setLayout(abaAcervoLayout);
        abaAcervoLayout.setHorizontalGroup(
            abaAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCargArqAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelLeCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        abaAcervoLayout.setVerticalGroup(
            abaAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelCargArqAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(painelLeCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Dados do acervo", abaAcervo);

        painelCargArqSIABI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carregar arquivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelCargArqSIABI.setToolTipText("Selecione um arquivo de texto simples (TXT) ou do Excel (XLS)");
        painelCargArqSIABI.setPreferredSize(new java.awt.Dimension(221, 210));

        botCargSIABI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_bd.png"))); // NOI18N
        botCargSIABI.setMnemonic(KeyEvent.VK_C);
        botCargSIABI.setText("Carregar arquivo");
        botCargSIABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCargSIABIActionPerformed(evt);
            }
        });

        jLabel5.setText("1º Passo:");

        jLabel6.setText("2º Passo:");

        botSelSIABI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_open.png"))); // NOI18N
        botSelSIABI.setMnemonic(KeyEvent.VK_S);
        botSelSIABI.setText("Selecionar arquivo");
        botSelSIABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSelSIABIActionPerformed(evt);
            }
        });

        endArqSIABI.setForeground(new java.awt.Color(204, 204, 204));
        endArqSIABI.setText("Nenhum arquivo selecionado");
        endArqSIABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endArqSIABIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCargArqSIABILayout = new javax.swing.GroupLayout(painelCargArqSIABI);
        painelCargArqSIABI.setLayout(painelCargArqSIABILayout);
        painelCargArqSIABILayout.setHorizontalGroup(
            painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCargArqSIABILayout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addGap(12, 12, 12))
            .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                .addGroup(painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botSelSIABI)
                            .addComponent(endArqSIABI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botCargSIABI))
                            .addComponent(jLabel6))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        painelCargArqSIABILayout.setVerticalGroup(
            painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endArqSIABI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botSelSIABI)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botCargSIABI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout abaSIABILayout = new javax.swing.GroupLayout(abaSIABI);
        abaSIABI.setLayout(abaSIABILayout);
        abaSIABILayout.setHorizontalGroup(
            abaSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaSIABILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCargArqSIABI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(751, Short.MAX_VALUE))
        );
        abaSIABILayout.setVerticalGroup(
            abaSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaSIABILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCargArqSIABI, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Dados do SIABI", abaSIABI);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerar relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel9.setToolTipText("Selecione um arquivo de texto simples (TXT) ou do Excel (XLS)");

        botGerRelat.setMnemonic(KeyEvent.VK_G);
        botGerRelat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_relatorio.png"))); // NOI18N
        botGerRelat.setText("Gerar");
        botGerRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botGerRelatActionPerformed(evt);
            }
        });

        comboRelat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Itens localizados no acervo", "Itens não localizados no acervo", "Itens não cadastrados no SIABI", "Itens localizados no acervo tidos como emprestados", "Itens para verificação" }));
        comboRelat.setToolTipText("Selecione o relatório a ser gerado");
        comboRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRelatActionPerformed(evt);
            }
        });
        comboRelat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboRelatKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(comboRelat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botGerRelat))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(comboRelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botGerRelat))
        );

        javax.swing.GroupLayout abaRelatoriosLayout = new javax.swing.GroupLayout(abaRelatorios);
        abaRelatorios.setLayout(abaRelatoriosLayout);
        abaRelatoriosLayout.setHorizontalGroup(
            abaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(529, Short.MAX_VALUE))
        );
        abaRelatoriosLayout.setVerticalGroup(
            abaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Relatórios", abaRelatorios);

        javax.swing.GroupLayout abaAjudaLayout = new javax.swing.GroupLayout(abaAjuda);
        abaAjuda.setLayout(abaAjudaLayout);
        abaAjudaLayout.setHorizontalGroup(
            abaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
        );
        abaAjudaLayout.setVerticalGroup(
            abaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        grupoAbas.addTab("Ajuda", abaAjuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grupoAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grupoAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Retorna a extensão de um arquivo
    private String getExtensao(File arq) {
        String extArq = null;
        String nomeArq = arq.getName();
        int i = nomeArq.lastIndexOf('.');

        if (i > 0 &&  i < nomeArq.length() - 1) {
            extArq = nomeArq.substring(i+1).toLowerCase();
        }
        return extArq;
    }
    
    //Um método estático pode ser chamdo a partir de outra classe (Obsevacoes)
    public /*static*/ void setObs(String obs){
        System.out.println("Fui chamado!");
        System.out.println(obs);
        obsIns = obs;
        //Modifica o valor do 3º argumento da tabela dos últimos códigos lidos
        //Chamar o método adequado aqui
    }
    
    public /*static*/ void setFocusBotaoInserir(){
        botInsCod.requestFocusInWindow();
    }
    
    public void setFocusCodBar(){
        codBar.requestFocusInWindow();
    }
    
    public static void setFocusUser(){
        userBD.requestFocusInWindow();
    }
    
    public void setFocusPswd(){
        pswdBD.requestFocusInWindow();
    }
    
    public void setFocusBotaoOk(){
        botOk.requestFocusInWindow();
    }
    
    public void desmarcarVrfExemplar(){
        //System.out.println("desmarcar");
        vrfExemplar.setSelected(false);
        vrfExemplar.setEnabled(true);
    }
    
    public void blockVrfExemplar(boolean b){
        //System.out.println("desmarcar");
        vrfExemplar.setEnabled(b);
    }
    
    public void travaLogin(){
        userBD.setEnabled(false);
        pswdBD.setEnabled(false);
        botOk.setEnabled(false);
        sesaoIni.setVisible(true);
        painelLogin.setToolTipText("A sessão será encerrada quando o programa for finalizado.");
        modeloTabelaUlt = dao.getLocalizacaoDosVizinhos(dao.getUltSeq());
        tabUltIni.setModel(modeloTabelaUlt);
    }
    
    private void botCargAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCargAcervoActionPerformed
        System.out.println("Chamar método para inserir no BD");
        try {
            System.out.println(endArqAcervo.getText());
            ManipulaXLS xls = new ManipulaXLS(dao);
                    
            xls.leXLS(endArqAcervo.getText());
            //xls.setRefInventarioDAO(dao);
        } catch (IOException ex) {
            System.out.println("Arquivo não selecionado");
            //Logger.getLogger(ManipulaXLS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botCargAcervoActionPerformed

    private void endArqAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endArqAcervoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endArqAcervoActionPerformed

    private void botCargSIABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCargSIABIActionPerformed
        System.out.println("Chamar método para inserir no BD");
        try {
            System.out.println(endArqSIABI.getText());
            ManipulaXLS xls = new ManipulaXLS(dao);
            
            if(xls.ehSIABI(endArqSIABI.getText())){
                xls.leXLS(endArqSIABI.getText());
            }
        } catch (IOException ex) {
            System.out.println("Arquivo não selecionado");
            //Logger.getLogger(ManipulaXLS.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_botCargSIABIActionPerformed

    private void endArqSIABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endArqSIABIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endArqSIABIActionPerformed
    //Falta tratar as extensões TXT e XLS
    //Falta tratar eventos, como no caso de digitar um endereço inexistente
    private void botSelAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSelAcervoActionPerformed
        int returnVal = fc.showOpenDialog(painelCargArqAcervo);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            
            File dir = fc.getCurrentDirectory();
            File arq = fc.getSelectedFile();
            //nomeArq = arq.getName();
            String endArq = arq.getAbsolutePath();
            //String endArq = dir + nomeArq;
            
            if(this.getExtensao(arq).equals("xls")){
            //System.out.println("Arquivo XLS aberto.");

                endArqAcervo.setForeground(new java.awt.Color(0, 0, 0));
                endArqAcervo.setText(endArq);
            }/*else{
            if(this.getExtensao(arq).equals("txt")){
            System.out.println("Arquivo TXT aberto.");
            }
            }*/
        }
            
    }//GEN-LAST:event_botSelAcervoActionPerformed

    private void insereDados() {
        String verificar = null;

        if (logado) {

            if ((codBar.getText() == null) || ("".equals(codBar.getText()))) {
                JOptionPane.showMessageDialog(null, "É necessário informar um código de barra!", null, JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                System.out.println("ENTROU!");
                
                if (vrfExemplar.isSelected()) {
                    verificar = "SIM";
                } else {
                    verificar = "-";
                }

                dadosIns.add(codBar.getText());
                dadosIns.add(verificar);
                dadosIns.add(obsIns);

                dao.insereLinha(dadosIns);

                dadosIns.clear();

                JOptionPane.showMessageDialog(null, "Inserção realizada com sucesso!");
                limpaTelaInsercao();
                modeloTabelaAcerv = dao.getTresUltimasLinhas();
                tabUltCod.setModel(modeloTabelaAcerv);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Insira um nome de usuário e senha válidos!", null, JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpaTelaInsercao(){
        codBar.setText("");
        desmarcarVrfExemplar();
        setFocusCodBar();
    }
    
    private void botSelSIABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSelSIABIActionPerformed
        int returnVal = fc.showOpenDialog(painelCargArqAcervo);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            
            File dir = fc.getCurrentDirectory();
            File arq = fc.getSelectedFile();
            //nomeArq = arq.getName();
            //String endArq = dir + nomeArq;
            String endArq = arq.getAbsolutePath();
            
            if(this.getExtensao(arq).equals("xls") || this.getExtensao(arq).equals("xlsx")){
            //System.out.println("Arquivo XLS aberto.");

                endArqSIABI.setForeground(new java.awt.Color(0, 0, 0));
                endArqSIABI.setText(endArq);
            }/*else{
            if(this.getExtensao(arq).equals("txt")){
            System.out.println("Arquivo TXT aberto.");
            }
            }*/
        }
    }//GEN-LAST:event_botSelSIABIActionPerformed

    private void botOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botOkActionPerformed
        dao.setRefInventarioUI(InventarioUI.this);
        logado = dao.login(userBD.getText(), pswdBD.getText());
        userBD.setText("");
        pswdBD.setText("");
        if(logado){
            System.out.println("LOGADO!");
                modeloTabelaUlt = dao.getLocalizacaoDosVizinhos(dao.getUltSeq());
                tabUltIni.setModel(modeloTabelaUlt);
        }
        
    }//GEN-LAST:event_botOkActionPerformed

    private void grupoAbasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grupoAbasFocusGained
        
    }//GEN-LAST:event_grupoAbasFocusGained

    private void abaAcervoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abaAcervoFocusGained
        //codBar.requestFocusInWindow();
        System.out.println("Aba ativa");
    }//GEN-LAST:event_abaAcervoFocusGained
    
    //Retorna a soma das dimensões dos JPanels de cada componente (neste caso abas) passado
    /*public Dimension getDimensaoComponents(Component c) {
    
    int larg = 0;
    int alt = 0;
    final int ADICIONAL = 20;
    
    Container container = (Container) c;
    
    for (int i = 0; i < container.getComponentCount(); i++) {
    
    Component comp = container.getComponent(i);
    
    if (comp instanceof JPanel) {
    
    JPanel painel = (JPanel) comp;
    
    larg = larg + painel.getHeight();
    alt = alt + painel.getWidth();
    }
    }
    System.out.println("larg: " + larg + ", alt: " + alt);
    larg = larg + ADICIONAL;
    alt = alt + ADICIONAL;
    
    return new Dimension(larg, alt);
    }*/
    
    
    //Muda os focos preferenciais dos componentes de cada aba de acordo com a que estiver selecionada
    private void grupoAbasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_grupoAbasStateChanged
        
        //InventarioUI.this.setPreferredSize(getDimensaoComponents(grupoAbas.getSelectedComponent()));
        /*   if (primChamada != true){
        this.setPreferredSize(getDimensaoComponents(grupoAbas.getSelectedComponent()));
        InventarioUI.this.pack();
        System.out.println("Pack");
        }*/
                
        InventarioUI.this.pack();
        
        if (grupoAbas.getSelectedComponent() == abaAcervo) {  
            //System.out.println ("Aba Acervo");  
            setFocusCodBar();
            if (logado) {
                dao.fechaConexao();

                modeloTabelaAcerv = dao.getTresUltimasLinhas();
                tabUltCod.setModel(modeloTabelaAcerv);
                
            }
        } else if (grupoAbas.getSelectedComponent() == abaInicio) {
            setFocusUser();
            if (logado) {
                
                dao.fechaConexao();

                modeloTabelaUlt = dao.getLocalizacaoDosVizinhos(dao.getUltSeq());
                tabUltIni.setModel(modeloTabelaUlt);
            }
        }

    }//GEN-LAST:event_grupoAbasStateChanged

    private void geraRelatorio(){
        GerenciadorRelatorios objGRD = null;
        System.out.println(comboRelat.getSelectedIndex());
        switch(comboRelat.getSelectedIndex()){
            case 0:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getLocalizados(), dao);
                break;
            case 1:
                //System.out.println((String) comboRelat.getSelectedItem());
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getNaoLocalizados(), dao);
                break;
            case 2:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getNaoCadastrados(), dao);
                break;
            case 3:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getLocalizadosMasEmprestados(), dao);
                break;
            case 4:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getItensParaVerificacao(), dao);
                break;

            default:
                System.out.println("Qualquer coisa!");
        }
        
        
        /*if ((comboRelat.getSelectedItem().equals("Itens não localizados no acervo"))){
        objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.mostraTabelaAcervo(), dao);
        System.out.println("Verdadeiro");
        
        }else {
        objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.mostraTabelaAcervoParcial(), dao);
        System.out.println("Falso");
        
        }*/
        
        //Passa a referência desta classe
        objGRD.setRefInventarioUI(InventarioUI.this);
        objGRD.setVisible(true);
    }
    
    private void botGerRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botGerRelatActionPerformed
        geraRelatorio();
        
    }//GEN-LAST:event_botGerRelatActionPerformed

    public static String getNomeRelatorio(){
        return (String) comboRelat.getSelectedItem();
    }
    
    private void userBDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userBDKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            setFocusPswd();
        }
    }//GEN-LAST:event_userBDKeyPressed

    private void pswdBDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswdBDKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Acho que tem que ter um bloco try catch em algum canto aqui
            dao.setRefInventarioUI(InventarioUI.this);
            logado = dao.login(userBD.getText(), pswdBD.getText());
            userBD.setText("");
            pswdBD.setText("");
            //requestFocus();
            //InventarioDAO.fazLogin(userBD.getText(), pswdBD.getText());
        }
    }//GEN-LAST:event_pswdBDKeyPressed

    private void comboRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRelatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRelatActionPerformed

    private void botDesfInsCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDesfInsCodActionPerformed
        dao.removerUltimaLinha();
        setFocusCodBar();
        modeloTabelaAcerv = dao.getTresUltimasLinhas();
        tabUltCod.setModel(modeloTabelaAcerv);
    }//GEN-LAST:event_botDesfInsCodActionPerformed

    private void botLimpCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpCodActionPerformed
        limpaTelaInsercao();
    }//GEN-LAST:event_botLimpCodActionPerformed

    private void botInsCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botInsCodKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.out.println("ENTER_BOTÃO INSERIR");
            insereDados();
        }
    }//GEN-LAST:event_botInsCodKeyPressed

    private void botInsCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInsCodActionPerformed
        insereDados();
    }//GEN-LAST:event_botInsCodActionPerformed

    private void vrfExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrfExemplarActionPerformed
        System.out.println("Botão clicado");

        /*Observacoes obs = new Observacoes();
        obs.setVisible(true);
        obs.setRefInventarioUI(this);*/
        Observacoes obsD = new Observacoes(InventarioUI.this, rootPaneCheckingEnabled);
        obsD.setRefInventarioUI(InventarioUI.this);
        obsD.setVisible(true);
    }//GEN-LAST:event_vrfExemplarActionPerformed

    private void codBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codBarKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            setFocusBotaoInserir();
        }
    }//GEN-LAST:event_codBarKeyPressed

    private void codBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codBarActionPerformed

    private void pswdBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdBDActionPerformed
        
        
    }//GEN-LAST:event_pswdBDActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("nada?");
        try {
            dao.fechaConexao();
            System.out.println("Janela fechada!");
        } catch (Exception e) {
        }finally{
        System.exit( 0 ); 
        //this.dispose();
        }
    }//GEN-LAST:event_formWindowClosed

    private void userBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userBDActionPerformed

    private void abaInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abaInicioFocusGained
        if(logado){
        
            /*modeloTabelaLocaliz = dao.getLocalizacaoDosVizinhos(dao.getUltSeq());
            tabLocaliz.setModel(modeloTabelaLocaliz);
            modeloTabelaTombo = dao.getTomboDosVizinhos(dao.getUltSeq());
            tabUltIni.setModel(modeloTabelaTombo);*/
        }
    }//GEN-LAST:event_abaInicioFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int i = JOptionPane.showConfirmDialog(null,
                "Deseja realmente sair?", null,
                JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            dao.fechaConexao();
            //System.exit(0);
            this.dispose();
        }
        //this.dispose();

    }//GEN-LAST:event_formWindowClosing

    private void comboRelatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboRelatKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            geraRelatorio();
        }
    }//GEN-LAST:event_comboRelatKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaAcervo;
    private javax.swing.JPanel abaAjuda;
    private javax.swing.JPanel abaInicio;
    private javax.swing.JPanel abaRelatorios;
    private javax.swing.JPanel abaSIABI;
    private javax.swing.JButton botCargAcervo;
    private javax.swing.JButton botCargSIABI;
    private javax.swing.JButton botDesfInsCod;
    private javax.swing.JButton botGerRelat;
    private javax.swing.JButton botInsCod;
    private javax.swing.JButton botLimpCod;
    private javax.swing.JButton botOk;
    private javax.swing.JButton botSelAcervo;
    private javax.swing.JButton botSelSIABI;
    private javax.swing.JTextField codBar;
    private static javax.swing.JComboBox<String> comboRelat;
    private javax.swing.JTextField endArqAcervo;
    private javax.swing.JTextField endArqSIABI;
    private javax.swing.JTabbedPane grupoAbas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel painelCargArqAcervo;
    private javax.swing.JPanel painelCargArqSIABI;
    private javax.swing.JPanel painelLeCodAcervo;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JTextField pswdBD;
    private javax.swing.JLabel sesaoIni;
    private javax.swing.JTable tabUltCod;
    private javax.swing.JTable tabUltIni;
    private static javax.swing.JTextField userBD;
    private javax.swing.JRadioButton vrfExemplar;
    // End of variables declaration//GEN-END:variables
}
