/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.uepb.bsc7.www.UI;


import com.br.uepb.bsc7.www.persistence.InventarioDAO;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Coordenação
 */
public class InventarioUI extends javax.swing.JFrame {

    JFileChooser fc = new JFileChooser();
    //Observacoes objObs = new Observacoes();
    //String nomeArq = null;
    private boolean primChamada;
    InventarioDAO dao = new InventarioDAO();
    ResultSet rs = null;
    ResultSetMetaData metadados = null;
    ArrayList<String> dadosIns = new ArrayList<>();
    //TableModel modeloTabelaLocaliz;
    //TableModel modeloTabelaTombo;
    TableModel modeloTabelaAcerv;
    TableModel modeloTabelaUlt;
    //public static boolean emExecucao = false;
    private boolean logado = false;
    private String obsIns = "";
    Cursor cursor = null;
    
    /**
     * Creates new form InventarioUI
     */
    public InventarioUI() {
        primChamada = true;
        initComponents();
        setFocusUser();
        labelProg.setVisible(false);
        labelPorc.setVisible(false);
        barraProg.setVisible(false);
        botBkp.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoAbas = new javax.swing.JTabbedPane();
        abaInicio = new javax.swing.JPanel();
        painelLogin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        userBD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pswdBD = new javax.swing.JPasswordField();
        botOk = new javax.swing.JButton();
        sessaoIni = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabUltIni = new javax.swing.JTable();
        abaEstante = new javax.swing.JPanel();
        painelCargArqAcervo = new javax.swing.JPanel();
        botCargEstante = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botSelEstante = new javax.swing.JButton();
        endArqEstante = new javax.swing.JTextField();
        painelLeCodAcervo = new javax.swing.JPanel();
        codBar = new javax.swing.JTextField();
        vrfExemplar = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabUltCod = new javax.swing.JTable();
        botInsCod = new javax.swing.JButton();
        botLimpCod = new javax.swing.JButton();
        botDesfInsCod = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abaSIABI = new javax.swing.JPanel();
        painelCargArqSIABI = new javax.swing.JPanel();
        botCargSIABI = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botSelSIABI = new javax.swing.JButton();
        endArqSIABI = new javax.swing.JTextField();
        labelProg = new javax.swing.JLabel();
        labelPorc = new javax.swing.JLabel();
        barraProg = new javax.swing.JProgressBar();
        abaRelatorios = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        botGerRelat = new javax.swing.JButton();
        comboRelat = new javax.swing.JComboBox<>();
        abaAjuda = new javax.swing.JPanel();
        botBkp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Inventário - UEPB");
        setIconImage(new ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_livros.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        grupoAbas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grupoAbas.setPreferredSize(new java.awt.Dimension(699, 200));
        grupoAbas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                grupoAbasStateChanged(evt);
            }
        });
        grupoAbas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                grupoAbasFocusGained(evt);
            }
        });

        abaInicio.setPreferredSize(new java.awt.Dimension(694, 200));
        abaInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                abaInicioFocusGained(evt);
            }
        });

        painelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel7.setText("Usuário:");

        userBD.setPreferredSize(new java.awt.Dimension(150, 22));
        userBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBDActionPerformed(evt);
            }
        });
        userBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userBDKeyPressed(evt);
            }
        });

        jLabel8.setText("Senha:");

        pswdBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdBDActionPerformed(evt);
            }
        });
        pswdBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswdBDKeyPressed(evt);
            }
        });

        botOk.setText("Ok");
        botOk.setMnemonic(KeyEvent.VK_O);
        botOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botOkActionPerformed(evt);
            }
        });

        sessaoIni.setText("Sessão iniciada!");
        sessaoIni.setVisible(false);

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswdBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                        .addComponent(botOk)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                        .addComponent(sessaoIni)
                        .addGap(45, 45, 45))))
        );

        painelLoginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pswdBD, userBD});

        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(userBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pswdBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sessaoIni)
                .addContainerGap())
        );

        painelLoginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pswdBD, userBD});

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Últimos valores inseridos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 153))); // NOI18N

        tabUltIni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tombo", "Localização (CDD)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabUltIni);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout abaInicioLayout = new javax.swing.GroupLayout(abaInicio);
        abaInicio.setLayout(abaInicioLayout);
        abaInicioLayout.setHorizontalGroup(
            abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaInicioLayout.setVerticalGroup(
            abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Início", abaInicio);

        abaEstante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                abaEstanteFocusGained(evt);
            }
        });

        painelCargArqAcervo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carregar arquivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelCargArqAcervo.setToolTipText("Selecione um arquivo de texto simples (TXT) ou do Excel (XLS)");
        painelCargArqAcervo.setPreferredSize(new java.awt.Dimension(221, 210));

        botCargEstante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_bd.png"))); // NOI18N
        botCargEstante.setMnemonic(KeyEvent.VK_C);
        botCargEstante.setText("Carregar arquivo");
        botCargEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCargEstanteActionPerformed(evt);
            }
        });

        jLabel3.setText("1º Passo:");

        jLabel4.setText("2º Passo:");

        botSelEstante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_open.png"))); // NOI18N
        botSelEstante.setMnemonic(KeyEvent.VK_S);
        botSelEstante.setText("Selecionar arquivo");
        botSelEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSelEstanteActionPerformed(evt);
            }
        });

        endArqEstante.setForeground(new java.awt.Color(204, 204, 204));
        endArqEstante.setText("Nenhum arquivo selecionado");
        endArqEstante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                endArqEstanteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                endArqEstanteFocusLost(evt);
            }
        });
        endArqEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endArqEstanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCargArqAcervoLayout = new javax.swing.GroupLayout(painelCargArqAcervo);
        painelCargArqAcervo.setLayout(painelCargArqAcervoLayout);
        painelCargArqAcervoLayout.setHorizontalGroup(
            painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCargArqAcervoLayout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addGap(12, 12, 12))
            .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                .addGroup(painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botSelEstante)
                            .addComponent(endArqEstante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botCargEstante))
                            .addComponent(jLabel4))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        painelCargArqAcervoLayout.setVerticalGroup(
            painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endArqEstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botSelEstante)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botCargEstante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelLeCodAcervo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Leitura de Código de Barras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelLeCodAcervo.setPreferredSize(new java.awt.Dimension(434, 210));

        codBar.setCaretPosition(0);
        codBar.setToolTipText("");
        codBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codBarActionPerformed(evt);
            }
        });
        codBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codBarKeyPressed(evt);
            }
        });

        vrfExemplar.setText("Verificar depois");
        vrfExemplar.setMnemonic(KeyEvent.VK_F);
        vrfExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrfExemplarActionPerformed(evt);
            }
        });

        tabUltCod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tombo", "Verificar", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabUltCod.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabUltCod);
        if (tabUltCod.getColumnModel().getColumnCount() > 0) {
            tabUltCod.getColumnModel().getColumn(1).setMinWidth(100);
            tabUltCod.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabUltCod.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        botInsCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_plus.png"))); // NOI18N
        botInsCod.setText("Inserir");
        botInsCod.setToolTipText("Insere o valor acima na tabela");
        botInsCod.setMnemonic(KeyEvent.VK_I);
        botInsCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInsCodActionPerformed(evt);
            }
        });
        botInsCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botInsCodKeyPressed(evt);
            }
        });

        botLimpCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_limpar.png"))); // NOI18N
        botLimpCod.setText("Limpar");
        botLimpCod.setToolTipText("Limpa os dados do campo acima");
        botLimpCod.setMnemonic(KeyEvent.VK_L);
        botLimpCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpCodActionPerformed(evt);
            }
        });

        botDesfInsCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_desfazer.png"))); // NOI18N
        botDesfInsCod.setText("Desfazer");
        botDesfInsCod.setToolTipText("Desfaz a última inserção de dado na tabela");
        botDesfInsCod.setMnemonic(KeyEvent.VK_D);
        botDesfInsCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDesfInsCodActionPerformed(evt);
            }
        });

        jLabel1.setText("Últimos códigos lidos");

        jLabel2.setText("Código");

        javax.swing.GroupLayout painelLeCodAcervoLayout = new javax.swing.GroupLayout(painelLeCodAcervo);
        painelLeCodAcervo.setLayout(painelLeCodAcervoLayout);
        painelLeCodAcervoLayout.setHorizontalGroup(
            painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLeCodAcervoLayout.createSequentialGroup()
                        .addComponent(codBar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vrfExemplar))
                    .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                        .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                                .addComponent(botInsCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botLimpCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botDesfInsCod))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLeCodAcervoLayout.setVerticalGroup(
            painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLeCodAcervoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vrfExemplar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botInsCod)
                    .addComponent(botLimpCod)
                    .addComponent(botDesfInsCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout abaEstanteLayout = new javax.swing.GroupLayout(abaEstante);
        abaEstante.setLayout(abaEstanteLayout);
        abaEstanteLayout.setHorizontalGroup(
            abaEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaEstanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCargArqAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelLeCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        abaEstanteLayout.setVerticalGroup(
            abaEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaEstanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelCargArqAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(painelLeCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Dados da estante", abaEstante);

        painelCargArqSIABI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carregar arquivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelCargArqSIABI.setToolTipText("Selecione um arquivo de texto simples (TXT) ou do Excel (XLS)");
        painelCargArqSIABI.setPreferredSize(new java.awt.Dimension(221, 210));

        botCargSIABI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_bd.png"))); // NOI18N
        botCargSIABI.setMnemonic(KeyEvent.VK_C);
        botCargSIABI.setText("Carregar arquivo");
        botCargSIABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCargSIABIActionPerformed(evt);
            }
        });

        jLabel5.setText("1º Passo:");

        jLabel6.setText("2º Passo:");

        botSelSIABI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_open.png"))); // NOI18N
        botSelSIABI.setMnemonic(KeyEvent.VK_S);
        botSelSIABI.setText("Selecionar arquivo");
        botSelSIABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSelSIABIActionPerformed(evt);
            }
        });

        endArqSIABI.setForeground(new java.awt.Color(204, 204, 204));
        endArqSIABI.setText("Nenhum arquivo selecionado");
        endArqSIABI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                endArqSIABIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                endArqSIABIFocusLost(evt);
            }
        });
        endArqSIABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endArqSIABIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCargArqSIABILayout = new javax.swing.GroupLayout(painelCargArqSIABI);
        painelCargArqSIABI.setLayout(painelCargArqSIABILayout);
        painelCargArqSIABILayout.setHorizontalGroup(
            painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                .addGroup(painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botSelSIABI))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6))
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(botCargSIABI))
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(endArqSIABI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCargArqSIABILayout.setVerticalGroup(
            painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endArqSIABI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botSelSIABI)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(botCargSIABI))
        );

        labelProg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_atencao.png"))); // NOI18N
        labelProg.setText("Aguarde enquanto os dados da planilha são inseridos no Banco de Dados.");

        barraProg.setStringPainted(true);

        javax.swing.GroupLayout abaSIABILayout = new javax.swing.GroupLayout(abaSIABI);
        abaSIABI.setLayout(abaSIABILayout);
        abaSIABILayout.setHorizontalGroup(
            abaSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaSIABILayout.createSequentialGroup()
                .addGroup(abaSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaSIABILayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelCargArqSIABI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(abaSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelPorc)
                            .addComponent(barraProg, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, abaSIABILayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(labelProg)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        abaSIABILayout.setVerticalGroup(
            abaSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaSIABILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCargArqSIABI, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
            .addGroup(abaSIABILayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(barraProg, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPorc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelProg)
                .addGap(25, 25, 25))
        );

        grupoAbas.addTab("Dados do SIABI", abaSIABI);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerar relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel9.setToolTipText("Selecione um arquivo de texto simples (TXT) ou do Excel (XLS)");

        botGerRelat.setMnemonic(KeyEvent.VK_G);
        botGerRelat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_relatorio.png"))); // NOI18N
        botGerRelat.setText("Gerar");
        botGerRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botGerRelatActionPerformed(evt);
            }
        });

        comboRelat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Itens localizados na estante", "Itens não localizados na estante", "Itens não cadastrados no SIABI", "Itens localizados na estante tidos como emprestados", "Itens marcados para verificação", "Todos itens lidos no inventário" }));
        comboRelat.setToolTipText("Selecione o relatório a ser gerado");
        comboRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRelatActionPerformed(evt);
            }
        });
        comboRelat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboRelatKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(comboRelat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botGerRelat))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(comboRelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botGerRelat))
        );

        javax.swing.GroupLayout abaRelatoriosLayout = new javax.swing.GroupLayout(abaRelatorios);
        abaRelatorios.setLayout(abaRelatoriosLayout);
        abaRelatoriosLayout.setHorizontalGroup(
            abaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        abaRelatoriosLayout.setVerticalGroup(
            abaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Relatórios", abaRelatorios);

        javax.swing.GroupLayout abaAjudaLayout = new javax.swing.GroupLayout(abaAjuda);
        abaAjuda.setLayout(abaAjudaLayout);
        abaAjudaLayout.setHorizontalGroup(
            abaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        abaAjudaLayout.setVerticalGroup(
            abaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        grupoAbas.addTab("Ajuda", abaAjuda);

        botBkp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_backup.png"))); // NOI18N
        botBkp.setToolTipText("Fazer backup do Banco de Dados");
        botBkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBkpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grupoAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botBkp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grupoAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botBkp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Retorna a extensão de um arquivo
    private String getExtensao(File arq) {
        String extArq = null;
        String nomeArq = arq.getName();
        int i = nomeArq.lastIndexOf('.');

        if (i > 0 &&  i < nomeArq.length() - 1) {
            extArq = nomeArq.substring(i+1).toLowerCase();
        }
        return extArq;
    }
    
    //Modifica o campo obs a ser inserido na tabela acervo_estante
    public  void setObs(String obs){
        
        System.out.println(obs);
        obsIns = obs;
    }
    
    public void setBarraProg(int valor){
        
        barraProg.setValue(valor);
    
    }
    
    public  void setFocusBotaoInserir(){
        botInsCod.requestFocusInWindow();
    }
    
    public void setFocusCodBar(){
        codBar.requestFocusInWindow();
    }
    
    public static void setFocusUser(){
        userBD.requestFocusInWindow();
    }
    
    public void setFocusPswd(){
        pswdBD.requestFocusInWindow();
    }
    
    public void setFocusBotaoOk(){
        botOk.requestFocusInWindow();
    }
    
    public void setFocusSelArqSIABI(){
        botSelSIABI.requestFocusInWindow();
    }
    
    public void desmarcarVrfExemplar(){
        vrfExemplar.setSelected(false);
        vrfExemplar.setEnabled(true);
    }
    
    public void blockVrfExemplar(boolean b){
        vrfExemplar.setEnabled(b);
    }
    
    public void travaLogin(){
        userBD.setEnabled(false);
        pswdBD.setEnabled(false);
        botOk.setEnabled(false);
        sessaoIni.setVisible(true);
        painelLogin.setToolTipText("A sessão será encerrada quando o programa for finalizado.");
        modeloTabelaUlt = dao.getLocalizacaoDosVizinhos(dao.getUltSeq());
        tabUltIni.setModel(modeloTabelaUlt);
    }
    
    private void botCargEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCargEstanteActionPerformed
        
        try {
        
            ManipulaXLS xls = new ManipulaXLS(dao);
            xls.leXLS(endArqEstante.getText());
            //xls.setRefInventarioDAO(dao);
        } catch (IOException ex) {
            JOptionPane.showConfirmDialog(null, "Arquivo não selecionado!", null, JOptionPane.INFORMATION_MESSAGE);
            //Logger.getLogger(ManipulaXLS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botCargEstanteActionPerformed

    private void endArqEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endArqEstanteActionPerformed
        if(endArqEstante.getText().equals("Nenhum arquivo selecionado")){
            endArqEstante.setText("");
            endArqEstante.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_endArqEstanteActionPerformed

    //Não funcional ainda
    //Tentativa de exibir na UI os valores de sequência sendo inseridos
    public void setLabelPorc(int valor){
        labelPorc.setText("Registro " + valor + " inserido!");
        labelPorc.repaint();
        abaSIABI.repaint();
        return;
    }
    
    private void botCargSIABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCargSIABIActionPerformed
        
        try {
            
            ManipulaXLS xls = new ManipulaXLS(dao);
            
            if(xls.ehSIABI(endArqSIABI.getText())){
                dao.deletaSIABI();
                dao.setRefInventarioUI(InventarioUI.this);
                travaAbas();
                xls.setRefInventarioUI(this);
                
                cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
                grupoAbas.setCursor(cursor);
                
                int tamTab = xls.getTamXLS(endArqSIABI.getText());
                
                barraProg.setMaximum(tamTab);
                
                labelProg.setVisible(true);
                labelPorc.setVisible(true);
                barraProg.setVisible(true);
                
                String msg = "Foram encontrados " + tamTab + " registros.";
                
                JOptionPane.showMessageDialog(null, msg + "\nEsta tarefa pode demorar um pouco. \nRecomenda-se não fazer uso de outras funções no computador \nenquanto a planilha estiver sendo carregada.", null, JOptionPane.INFORMATION_MESSAGE);
                
                
                xls.leXLS(endArqSIABI.getText());
                
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Arquivo não selecionado!", null, JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(ManipulaXLS.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            
            //labelProg.setVisible(false);
            //barraProg.setVisible(false);
        
        }
        
    }//GEN-LAST:event_botCargSIABIActionPerformed

    public void acabouSIABI() {

        destravaAbas();
        cursor = Cursor.getDefaultCursor();
        grupoAbas.setCursor(cursor);
        labelProg.setVisible(false);
        labelPorc.setVisible(false);
        barraProg.setVisible(false);
            
    }
        //Falta tratar a extensão TXT
    //Falta tratar eventos, como no caso de digitar um endereço inexistente
    private void botSelEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSelEstanteActionPerformed
        
        abreArq(1);
    }//GEN-LAST:event_botSelEstanteActionPerformed

    public void abreArq(int i) {

        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File dir = fc.getCurrentDirectory();
            File arq = fc.getSelectedFile();
            String endArq = arq.getAbsolutePath();

            if (this.getExtensao(arq).equals("xls") || this.getExtensao(arq).equals("xlsx")) {

                switch (i) {

                    case 1:

                        setEndArqEstante(endArq);
                        break;

                    case 2:

                        setEndArqSIABI(endArq);
                        break;

                }
            }
        }
    }
    
    private void insereDados() {
        String verificar = null;

        if (logado) {

            if ((codBar.getText() == null) || ("".equals(codBar.getText()))) {
                JOptionPane.showMessageDialog(null, "É necessário informar um código de barra!", null, JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                
                
                if (vrfExemplar.isSelected()) {
                    verificar = "SIM";
                } else {
                    verificar = "-";
                }
                
                if(!dao.estahCadastradoNoSIABI(codBar.getText())){
                    if(vrfExemplar.isSelected()){
                        obsIns = obsIns + "Não cadastrado!";
                    }else{
                        verificar = "SIM";
                        obsIns = " Não cadastrado!";
                    }
                } else {
                    if(!vrfExemplar.isSelected()){
                        obsIns = "";
                    }
                }

                dadosIns.add(codBar.getText());
                dadosIns.add(verificar);
                dadosIns.add(obsIns);
                
                dao.insereLinha(dadosIns);

                dadosIns.clear();
                
                JOptionPane.showMessageDialog(null, "Inserção realizada com sucesso!");
                
                if(!dao.estahCadastradoNoSIABI(codBar.getText())){
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "O código lido não está cadastrado no SIABI!", null, JOptionPane.ERROR_MESSAGE);
                } 
                
                limpaTelaInsercao();
                modeloTabelaAcerv = dao.getTresUltimasLinhas();
                tabUltCod.setModel(modeloTabelaAcerv);
                
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Insira um nome de usuário e senha válidos!", null, JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpaTelaInsercao(){
        codBar.setText("");
        desmarcarVrfExemplar();
        setFocusCodBar();
    }
    
    private void botSelSIABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSelSIABIActionPerformed
        abreArq(2);
    }//GEN-LAST:event_botSelSIABIActionPerformed

    private void botOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botOkActionPerformed
        dao.setRefInventarioUI(InventarioUI.this);
        logado = dao.login(userBD.getText(), pswdBD.getText());
        userBD.setText("");
        pswdBD.setText("");
        if(logado){
            modeloTabelaUlt = dao.getLocalizacaoDosVizinhos(dao.getUltSeq());
            tabUltIni.setModel(modeloTabelaUlt);
        }else{
            setFocusUser();
        }
        
    }//GEN-LAST:event_botOkActionPerformed

    private void grupoAbasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grupoAbasFocusGained
        
    }//GEN-LAST:event_grupoAbasFocusGained

    private void abaEstanteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abaEstanteFocusGained
        
        
    }//GEN-LAST:event_abaEstanteFocusGained
    
    //Retorna a soma das dimensões dos JPanels de cada componente (neste caso abas) passado
    /*public Dimension getDimensaoComponents(Component c) {
    
    int larg = 0;
    int alt = 0;
    final int ADICIONAL = 20;
    
    Container container = (Container) c;
    
    for (int i = 0; i < container.getComponentCount(); i++) {
    
    Component comp = container.getComponent(i);
    
    if (comp instanceof JPanel) {
    
    JPanel painel = (JPanel) comp;
    
    larg = larg + painel.getHeight();
    alt = alt + painel.getWidth();
    }
    }
    System.out.println("larg: " + larg + ", alt: " + alt);
    larg = larg + ADICIONAL;
    alt = alt + ADICIONAL;
    
    return new Dimension(larg, alt);
    }*/
    
    
    private void travaAbas(){
    
        abaInicio.setEnabled(false);
        abaEstante.setEnabled(false);
        abaRelatorios.setEnabled(false);
        abaAjuda.setEnabled(false);
        
        
    }
    
    private void destravaAbas(){
    
        abaInicio.setEnabled(true);
        abaEstante.setEnabled(true);
        abaRelatorios.setEnabled(true);
        abaAjuda.setEnabled(true);
        
        
    }
    
    //Muda os focos preferenciais dos componentes de cada aba de acordo com a que estiver selecionada
    private void grupoAbasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_grupoAbasStateChanged
        
                
        InventarioUI.this.pack();
        
        if (grupoAbas.getSelectedComponent() == abaEstante) {  
            //System.out.println ("Aba Acervo");  
            setFocusCodBar();
            if (logado) {
                dao.fechaConexao();

                modeloTabelaAcerv = dao.getTresUltimasLinhas();
                tabUltCod.setModel(modeloTabelaAcerv);
                
            }
        } else if (grupoAbas.getSelectedComponent() == abaInicio) {
            setFocusUser();
            if (logado) {
                
                dao.fechaConexao();

                modeloTabelaUlt = dao.getLocalizacaoDosVizinhos(dao.getUltSeq());
                tabUltIni.setModel(modeloTabelaUlt);
            }
        } else if (grupoAbas.getSelectedComponent() == abaSIABI) {  
            setFocusSelArqSIABI();
        
        }

    }//GEN-LAST:event_grupoAbasStateChanged

    private void geraRelatorio(){
        GerenciadorRelatorios objGRD = null;
        
        switch(comboRelat.getSelectedIndex()){
            case 0:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getLocalizados(), dao);
                break;
            case 1:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getNaoLocalizados(), dao);
                break;
            case 2:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getNaoCadastrados(), dao);
                break;
            case 3:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getLocalizadosMasEmprestados(), dao);
                break;
            case 4:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getItensParaVerificacao(), dao);
                break;
            case 5:
                objGRD = new GerenciadorRelatorios(InventarioUI.this, true, dao.getExemplaresLidos(), dao);
                break;
    

            default:
                System.out.println("Qualquer coisa!");
        }
        
        //Passa a referência desta classe
        objGRD.setRefInventarioUI(InventarioUI.this);
        objGRD.setVisible(true);
    }
    
    private void botGerRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botGerRelatActionPerformed
        geraRelatorio();
        
    }//GEN-LAST:event_botGerRelatActionPerformed

    public static String getNomeRelatorio(){
        return (String) comboRelat.getSelectedItem();
    }
    
    private void userBDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userBDKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            setFocusPswd();
        }
    }//GEN-LAST:event_userBDKeyPressed

    private void pswdBDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswdBDKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Acho que tem que ter um bloco try catch em algum canto aqui
            dao.setRefInventarioUI(InventarioUI.this);
            logado = dao.login(userBD.getText(), pswdBD.getText());
            userBD.setText("");
            pswdBD.setText("");
            if (logado) {
                modeloTabelaUlt = dao.getLocalizacaoDosVizinhos(dao.getUltSeq());
                tabUltIni.setModel(modeloTabelaUlt);
            }
        }
    }//GEN-LAST:event_pswdBDKeyPressed

    private void comboRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRelatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRelatActionPerformed

    private void botDesfInsCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDesfInsCodActionPerformed
        dao.removerUltimaLinha();
        setFocusCodBar();
        modeloTabelaAcerv = dao.getTresUltimasLinhas();
        tabUltCod.setModel(modeloTabelaAcerv);
    }//GEN-LAST:event_botDesfInsCodActionPerformed

    private void botLimpCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpCodActionPerformed
        limpaTelaInsercao();
    }//GEN-LAST:event_botLimpCodActionPerformed

    private void botInsCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botInsCodKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            insereDados();
        }
    }//GEN-LAST:event_botInsCodKeyPressed

    private void botInsCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInsCodActionPerformed
        insereDados();
    }//GEN-LAST:event_botInsCodActionPerformed

    private void vrfExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrfExemplarActionPerformed
        

        Observacoes obsD = new Observacoes(InventarioUI.this, rootPaneCheckingEnabled);
        obsD.setRefInventarioUI(InventarioUI.this);
        obsD.setVisible(true);
    }//GEN-LAST:event_vrfExemplarActionPerformed

    private void codBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codBarKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            setFocusBotaoInserir();
        }
    }//GEN-LAST:event_codBarKeyPressed

    private void codBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codBarActionPerformed

    private void pswdBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdBDActionPerformed
        
        
    }//GEN-LAST:event_pswdBDActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void userBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userBDActionPerformed

    private void abaInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abaInicioFocusGained
        
    }//GEN-LAST:event_abaInicioFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int i = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", null, JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            dao.fechaConexao();
            this.dispose();
        } else if (i == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_formWindowClosing

    private void comboRelatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboRelatKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            geraRelatorio();
        }
    }//GEN-LAST:event_comboRelatKeyPressed

    private void endArqEstanteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_endArqEstanteFocusGained
        if (endArqEstante.getText().equals("Nenhum arquivo selecionado")) {
            endArqEstante.setText("");
            endArqEstante.setForeground(new java.awt.Color(0, 0, 0));        
        }
    }//GEN-LAST:event_endArqEstanteFocusGained

    private void endArqEstanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_endArqEstanteFocusLost
        if (endArqEstante.getText().equals("")){
            endArqEstante.setText("Nenhum arquivo selecionado");
            endArqEstante.setForeground(new java.awt.Color(204, 204, 204));
        }      
    }//GEN-LAST:event_endArqEstanteFocusLost

    private void endArqSIABIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_endArqSIABIFocusGained
        if (endArqSIABI.getText().equals("Nenhum arquivo selecionado")) {
            endArqSIABI.setText("");
            endArqSIABI.setForeground(new java.awt.Color(0, 0, 0));        
        }
    }//GEN-LAST:event_endArqSIABIFocusGained

    private void endArqSIABIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_endArqSIABIFocusLost
        if (endArqSIABI.getText().equals("")){
            endArqSIABI.setText("Nenhum arquivo selecionado");
            endArqSIABI.setForeground(new java.awt.Color(204, 204, 204));
        }      
    }//GEN-LAST:event_endArqSIABIFocusLost

    private void endArqSIABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endArqSIABIActionPerformed
        if(endArqSIABI.getText().equals("Nenhum arquivo selecionado")){
           endArqSIABI.setText("");
           endArqSIABI.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_endArqSIABIActionPerformed

    private void botBkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBkpActionPerformed
        dao.fazBackup();
    }//GEN-LAST:event_botBkpActionPerformed

    public void setEndArqEstante(String end){
        endArqEstante.setForeground(new java.awt.Color(0, 0, 0));
        endArqEstante.setText(end);
    }
    
    public void setEndArqSIABI(String end){
        endArqSIABI.setForeground(new java.awt.Color(0, 0, 0));
        endArqSIABI.setText(end);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaAjuda;
    private javax.swing.JPanel abaEstante;
    private javax.swing.JPanel abaInicio;
    private javax.swing.JPanel abaRelatorios;
    private javax.swing.JPanel abaSIABI;
    private javax.swing.JProgressBar barraProg;
    private javax.swing.JButton botBkp;
    private javax.swing.JButton botCargEstante;
    private javax.swing.JButton botCargSIABI;
    private javax.swing.JButton botDesfInsCod;
    private javax.swing.JButton botGerRelat;
    private javax.swing.JButton botInsCod;
    private javax.swing.JButton botLimpCod;
    private javax.swing.JButton botOk;
    private javax.swing.JButton botSelEstante;
    private javax.swing.JButton botSelSIABI;
    private javax.swing.JTextField codBar;
    private static javax.swing.JComboBox<String> comboRelat;
    private javax.swing.JTextField endArqEstante;
    private javax.swing.JTextField endArqSIABI;
    private javax.swing.JTabbedPane grupoAbas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JLabel labelPorc;
    private javax.swing.JLabel labelProg;
    private javax.swing.JPanel painelCargArqAcervo;
    private javax.swing.JPanel painelCargArqSIABI;
    private javax.swing.JPanel painelLeCodAcervo;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JTextField pswdBD;
    private javax.swing.JLabel sessaoIni;
    private javax.swing.JTable tabUltCod;
    private javax.swing.JTable tabUltIni;
    private static javax.swing.JTextField userBD;
    private javax.swing.JRadioButton vrfExemplar;
    // End of variables declaration//GEN-END:variables
}
