/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.uepb.bsc7.www.UI;

import com.br.uepb.bsc7.www.persistence.InventarioDAO;
import com.br.uepb.bsc7.www.persistence.TabelaRelatorio;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Coordenação
 */
public class InventarioUI extends javax.swing.JFrame {

    JFileChooser fc = new JFileChooser();
    //Observacoes objObs = new Observacoes();
    //String nomeArq = null;
    private boolean primChamada;
    InventarioDAO dao = new InventarioDAO();
    ResultSet rs = null;
    ResultSetMetaData metadados = null;
    
    /**
     * Creates new form InventarioUI
     */
    public InventarioUI() {
        primChamada = true;
        initComponents();
        setFocusUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoAbas = new javax.swing.JTabbedPane();
        abaInicio = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        userBD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pswdBD = new javax.swing.JPasswordField();
        botOk = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabUltIni = new javax.swing.JTable();
        abaAcervo = new javax.swing.JPanel();
        painelCargArqAcervo = new javax.swing.JPanel();
        botCargAcervo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botSelAcervo = new javax.swing.JButton();
        endArqAcervo = new javax.swing.JTextField();
        painelLeCodAcervo = new javax.swing.JPanel();
        codBar = new javax.swing.JTextField();
        vrfExemplar = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabUltCod = new javax.swing.JTable();
        botInsCod = new javax.swing.JButton();
        botLimpCod = new javax.swing.JButton();
        botDesfInsCod = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abaSIABI = new javax.swing.JPanel();
        painelCargArqSIABI = new javax.swing.JPanel();
        botCargSIABI = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botSelSIABI = new javax.swing.JButton();
        endArqSIABI = new javax.swing.JTextField();
        abaRelatorios = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        botGerRelat = new javax.swing.JButton();
        comboRelat = new javax.swing.JComboBox<>();
        abaAjuda = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(723, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        grupoAbas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grupoAbas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                grupoAbasStateChanged(evt);
            }
        });
        grupoAbas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                grupoAbasFocusGained(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel7.setText("Usuário:");

        userBD.setPreferredSize(new java.awt.Dimension(150, 22));
        userBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userBDKeyPressed(evt);
            }
        });

        jLabel8.setText("Senha:");

        pswdBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdBDActionPerformed(evt);
            }
        });
        pswdBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswdBDKeyPressed(evt);
            }
        });

        botOk.setText("Ok");
        botOk.setMnemonic(KeyEvent.VK_O);
        botOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswdBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botOk)
                .addGap(68, 68, 68))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pswdBD, userBD});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(userBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pswdBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botOk)
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pswdBD, userBD});

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Últimos valores inseridos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 153))); // NOI18N

        tabUltIni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CDD", "Tombo", "Tombo Anterior 1", "Tombo Anterior 2", "Tombo Posterior 1", "Tombo Posterior 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabUltIni.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabUltIni.getTableHeader().setResizingAllowed(false);
        tabUltIni.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabUltIni);
        if (tabUltIni.getColumnModel().getColumnCount() > 0) {
            tabUltIni.getColumnModel().getColumn(1).setMinWidth(100);
            tabUltIni.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabUltIni.getColumnModel().getColumn(1).setMaxWidth(100);
        }
        for (int i = 0; i < tabUltIni.getColumnCount(); i++){

            Font font = tabUltIni.getFont();
            FontMetrics fmetrics = this.getFontMetrics(font);

            int comprString = fmetrics.stringWidth(tabUltIni.getColumnName(i));
            tabUltIni.getColumnModel().getColumn(i).setMinWidth(comprString + 10);

        }

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout abaInicioLayout = new javax.swing.GroupLayout(abaInicio);
        abaInicio.setLayout(abaInicioLayout);
        abaInicioLayout.setHorizontalGroup(
            abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        abaInicioLayout.setVerticalGroup(
            abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Início", abaInicio);

        abaAcervo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                abaAcervoFocusGained(evt);
            }
        });

        painelCargArqAcervo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carregar arquivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelCargArqAcervo.setToolTipText("Selecione um arquivo de texto simples (TXT) ou do Excel (XLS)");

        botCargAcervo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_bd.png"))); // NOI18N
        botCargAcervo.setMnemonic(KeyEvent.VK_C);
        botCargAcervo.setText("Carregar arquivo");
        botCargAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCargAcervoActionPerformed(evt);
            }
        });

        jLabel3.setText("1º Passo:");

        jLabel4.setText("2º Passo:");

        botSelAcervo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_open.png"))); // NOI18N
        botSelAcervo.setMnemonic(KeyEvent.VK_S);
        botSelAcervo.setText("Selecionar arquivo");
        botSelAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSelAcervoActionPerformed(evt);
            }
        });

        endArqAcervo.setForeground(new java.awt.Color(204, 204, 204));
        endArqAcervo.setText("Nenhum arquivo selecionado");
        endArqAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endArqAcervoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCargArqAcervoLayout = new javax.swing.GroupLayout(painelCargArqAcervo);
        painelCargArqAcervo.setLayout(painelCargArqAcervoLayout);
        painelCargArqAcervoLayout.setHorizontalGroup(
            painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCargArqAcervoLayout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addGap(12, 12, 12))
            .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                .addGroup(painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botSelAcervo)
                            .addComponent(endArqAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botCargAcervo))
                            .addComponent(jLabel4))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        painelCargArqAcervoLayout.setVerticalGroup(
            painelCargArqAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCargArqAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endArqAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botSelAcervo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botCargAcervo)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        painelLeCodAcervo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Leitura de Código de Barras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        codBar.setCaretPosition(0);
        codBar.setToolTipText("");
        codBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codBarActionPerformed(evt);
            }
        });
        codBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codBarKeyPressed(evt);
            }
        });

        vrfExemplar.setText("Verificar depois");
        vrfExemplar.setMnemonic(KeyEvent.VK_F);
        vrfExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrfExemplarActionPerformed(evt);
            }
        });

        tabUltCod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tombo", "Verificar", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabUltCod.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabUltCod);
        if (tabUltCod.getColumnModel().getColumnCount() > 0) {
            tabUltCod.getColumnModel().getColumn(1).setMinWidth(100);
            tabUltCod.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabUltCod.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        botInsCod.setText("Inserir");
        botInsCod.setToolTipText("Insere o valor acima na tabela");
        botInsCod.setMnemonic(KeyEvent.VK_I);
        botInsCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInsCodActionPerformed(evt);
            }
        });
        botInsCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botInsCodKeyPressed(evt);
            }
        });

        botLimpCod.setText("Limpar");
        botLimpCod.setToolTipText("Limpa os dados do campo acima");
        botLimpCod.setMnemonic(KeyEvent.VK_L);
        botLimpCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpCodActionPerformed(evt);
            }
        });

        botDesfInsCod.setText("Desfazer");
        botDesfInsCod.setToolTipText("Desfaz a última inserção de dado na tabela");
        botDesfInsCod.setMnemonic(KeyEvent.VK_D);
        botDesfInsCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDesfInsCodActionPerformed(evt);
            }
        });

        jLabel1.setText("Últimos códigos lidos");

        jLabel2.setText("Código");

        javax.swing.GroupLayout painelLeCodAcervoLayout = new javax.swing.GroupLayout(painelLeCodAcervo);
        painelLeCodAcervo.setLayout(painelLeCodAcervoLayout);
        painelLeCodAcervoLayout.setHorizontalGroup(
            painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLeCodAcervoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                                .addComponent(codBar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vrfExemplar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelLeCodAcervoLayout.createSequentialGroup()
                                .addComponent(botInsCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botLimpCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botDesfInsCod)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                        .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel1))
                            .addGroup(painelLeCodAcervoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelLeCodAcervoLayout.setVerticalGroup(
            painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLeCodAcervoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vrfExemplar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLeCodAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botInsCod)
                    .addComponent(botLimpCod)
                    .addComponent(botDesfInsCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout abaAcervoLayout = new javax.swing.GroupLayout(abaAcervo);
        abaAcervo.setLayout(abaAcervoLayout);
        abaAcervoLayout.setHorizontalGroup(
            abaAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCargArqAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelLeCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaAcervoLayout.setVerticalGroup(
            abaAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelLeCodAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(painelCargArqAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        grupoAbas.addTab("Dados do acervo", abaAcervo);

        painelCargArqSIABI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carregar arquivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelCargArqSIABI.setToolTipText("Selecione um arquivo de texto simples (TXT) ou do Excel (XLS)");
        painelCargArqSIABI.setPreferredSize(new java.awt.Dimension(221, 265));

        botCargSIABI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_bd.png"))); // NOI18N
        botCargSIABI.setMnemonic(KeyEvent.VK_C);
        botCargSIABI.setText("Carregar arquivo");
        botCargSIABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCargSIABIActionPerformed(evt);
            }
        });

        jLabel5.setText("1º Passo:");

        jLabel6.setText("2º Passo:");

        botSelSIABI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_open.png"))); // NOI18N
        botSelSIABI.setMnemonic(KeyEvent.VK_S);
        botSelSIABI.setText("Selecionar arquivo");
        botSelSIABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSelSIABIActionPerformed(evt);
            }
        });

        endArqSIABI.setForeground(new java.awt.Color(204, 204, 204));
        endArqSIABI.setText("Nenhum arquivo selecionado");
        endArqSIABI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endArqSIABIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCargArqSIABILayout = new javax.swing.GroupLayout(painelCargArqSIABI);
        painelCargArqSIABI.setLayout(painelCargArqSIABILayout);
        painelCargArqSIABILayout.setHorizontalGroup(
            painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCargArqSIABILayout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addGap(12, 12, 12))
            .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                .addGroup(painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botSelSIABI)
                            .addComponent(endArqSIABI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botCargSIABI))
                            .addComponent(jLabel6))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        painelCargArqSIABILayout.setVerticalGroup(
            painelCargArqSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCargArqSIABILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endArqSIABI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botSelSIABI)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botCargSIABI)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout abaSIABILayout = new javax.swing.GroupLayout(abaSIABI);
        abaSIABI.setLayout(abaSIABILayout);
        abaSIABILayout.setHorizontalGroup(
            abaSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaSIABILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCargArqSIABI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        abaSIABILayout.setVerticalGroup(
            abaSIABILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaSIABILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCargArqSIABI, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Dados do SIABI", abaSIABI);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerar relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel9.setToolTipText("Selecione um arquivo de texto simples (TXT) ou do Excel (XLS)");

        botGerRelat.setMnemonic(KeyEvent.VK_G);
        botGerRelat.setText("Gerar");
        botGerRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botGerRelatActionPerformed(evt);
            }
        });

        comboRelat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Itens localizados no acervo", "Itens não localizados no acervo", "Itens não cadastrados no SIABI", "Itens localizados no acervo tidos como emprestados", "Itens para verificação" }));
        comboRelat.setToolTipText("Selecione o relatório a ser gerado");
        comboRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRelatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(comboRelat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botGerRelat))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(comboRelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botGerRelat))
        );

        javax.swing.GroupLayout abaRelatoriosLayout = new javax.swing.GroupLayout(abaRelatorios);
        abaRelatorios.setLayout(abaRelatoriosLayout);
        abaRelatoriosLayout.setHorizontalGroup(
            abaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        abaRelatoriosLayout.setVerticalGroup(
            abaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Relatórios", abaRelatorios);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaAjudaLayout = new javax.swing.GroupLayout(abaAjuda);
        abaAjuda.setLayout(abaAjudaLayout);
        abaAjudaLayout.setHorizontalGroup(
            abaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAjudaLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jButton1)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        abaAjudaLayout.setVerticalGroup(
            abaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaAjudaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton1)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        grupoAbas.addTab("Ajuda", abaAjuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grupoAbas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(grupoAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Retorna a extensão de um arquivo
    private String getExtensao(File arq) {
        String extArq = null;
        String nomeArq = arq.getName();
        int i = nomeArq.lastIndexOf('.');

        if (i > 0 &&  i < nomeArq.length() - 1) {
            extArq = nomeArq.substring(i+1).toLowerCase();
        }
        return extArq;
    }
    
    //Um método estático pode ser chamdo a partir de outra classe (Obsevacoes)
    public /*static*/ void setObs(String obs){
        System.out.println("Fui chamado!");
        System.out.println(obs);
        //Modifica o valor do 3º argumento da tabela dos últimos códigos lidos
        //Chamar o método adequado aqui
    }
    
    public /*static*/ void setFocusBotaoInserir(){
        botInsCod.requestFocusInWindow();
    }
    
    public void setFocusCodBar(){
        codBar.requestFocusInWindow();
    }
    
    public void setFocusUser(){
        userBD.requestFocusInWindow();
    }
    
    public void setFocusPswd(){
        pswdBD.requestFocusInWindow();
    }
    
    public void setFocusBotaoOk(){
        botOk.requestFocusInWindow();
    }
    
    public void desmarcarVrfExemplar(){
        //System.out.println("desmarcar");
        vrfExemplar.setSelected(false);
    }
    
    private void botCargAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCargAcervoActionPerformed
        System.out.println("Chamar método para inserir no BD");
        try {
            System.out.println(endArqAcervo.getText());
            ManipulaXLS xls = new ManipulaXLS(dao);
                    
            xls.leXLS(endArqAcervo.getText());
            //xls.setRefInventarioDAO(dao);
            
            
        } catch (IOException ex) {
            System.out.println("Arquivo não selecionado");
            //Logger.getLogger(ManipulaXLS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botCargAcervoActionPerformed

    private void endArqAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endArqAcervoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endArqAcervoActionPerformed

    private void botCargSIABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCargSIABIActionPerformed
        System.out.println("Chamar método para inserir no BD");
        try {
            new ManipulaXLS().leXLS(endArqSIABI.getText());
        } catch (IOException ex) {
            System.out.println("Arquivo não selecionado");
            //Logger.getLogger(ManipulaXLS.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_botCargSIABIActionPerformed

    private void endArqSIABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endArqSIABIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endArqSIABIActionPerformed
    //Falta tratar as extensões TXT e XLS
    //Falta tratar eventos, como no caso de digitar um endereço inexistente
    private void botSelAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSelAcervoActionPerformed
        int returnVal = fc.showOpenDialog(painelCargArqAcervo);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            
            File dir = fc.getCurrentDirectory();
            File arq = fc.getSelectedFile();
            //nomeArq = arq.getName();
            String endArq = arq.getAbsolutePath();
            //String endArq = dir + nomeArq;
            
            if(this.getExtensao(arq).equals("xls")){
            //System.out.println("Arquivo XLS aberto.");

                endArqAcervo.setForeground(new java.awt.Color(0, 0, 0));
                endArqAcervo.setText(endArq);
            }/*else{
            if(this.getExtensao(arq).equals("txt")){
            System.out.println("Arquivo TXT aberto.");
            }
            }*/
        }
            
    }//GEN-LAST:event_botSelAcervoActionPerformed

    private void insereDados(){
    //Chama a versão adequada do método insereDadosBD() de DAO
        JOptionPane.showMessageDialog(null, "Inserção realizada com sucesso!");
        limpaTelaInsercao();
    }
    private void limpaTelaInsercao(){
        codBar.setText("");
        desmarcarVrfExemplar();
        setFocusCodBar();
    }
    
    private void botSelSIABIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSelSIABIActionPerformed
        int returnVal = fc.showOpenDialog(painelCargArqAcervo);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            
            File dir = fc.getCurrentDirectory();
            File arq = fc.getSelectedFile();
            //nomeArq = arq.getName();
            //String endArqSIABI = dir + nomeArq;
            String endArqSIABI = arq.getAbsolutePath();
            
            if(this.getExtensao(arq).equals("xls")){
            //System.out.println("Arquivo XLS aberto.");

                endArqAcervo.setForeground(new java.awt.Color(0, 0, 0));
                endArqAcervo.setText(endArqSIABI);
            }/*else{
            if(this.getExtensao(arq).equals("txt")){
            System.out.println("Arquivo TXT aberto.");
            }
            }*/
        }
    }//GEN-LAST:event_botSelSIABIActionPerformed

    private void botOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botOkActionPerformed
        
        dao.login(userBD.getText(), pswdBD.getText());
        userBD.setText("");
        pswdBD.setText("");
    }//GEN-LAST:event_botOkActionPerformed

    private void grupoAbasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grupoAbasFocusGained
        
    }//GEN-LAST:event_grupoAbasFocusGained

    private void abaAcervoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abaAcervoFocusGained
        //codBar.requestFocusInWindow();
        System.out.println("Aba ativa");
    }//GEN-LAST:event_abaAcervoFocusGained
    
    //Retorna a soma das dimensões dos JPanels de cada componente (neste caso abas) passado
    /*public Dimension getDimensaoComponents(Component c) {
    
    int larg = 0;
    int alt = 0;
    final int ADICIONAL = 20;
    
    Container container = (Container) c;
    
    for (int i = 0; i < container.getComponentCount(); i++) {
    
    Component comp = container.getComponent(i);
    
    if (comp instanceof JPanel) {
    
    JPanel painel = (JPanel) comp;
    
    larg = larg + painel.getHeight();
    alt = alt + painel.getWidth();
    }
    }
    System.out.println("larg: " + larg + ", alt: " + alt);
    larg = larg + ADICIONAL;
    alt = alt + ADICIONAL;
    
    return new Dimension(larg, alt);
    }*/
    
    
    //Muda os focos preferenciais dos componentes de cada aba de acordo com a que estiver selecionada
    private void grupoAbasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_grupoAbasStateChanged
        
        //InventarioUI.this.setPreferredSize(getDimensaoComponents(grupoAbas.getSelectedComponent()));
        /*   if (primChamada != true){
        this.setPreferredSize(getDimensaoComponents(grupoAbas.getSelectedComponent()));
        InventarioUI.this.pack();
        System.out.println("Pack");
        }*/
        
        InventarioUI.this.pack();
        
        if (grupoAbas.getSelectedComponent() == abaAcervo) {  
            //System.out.println ("Aba Acervo");  
            setFocusCodBar();
        }  else if (grupoAbas.getSelectedComponent() == abaInicio) {  
            setFocusUser();
        }  
        
    }//GEN-LAST:event_grupoAbasStateChanged

    private void botGerRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botGerRelatActionPerformed
        //Cria objeto passando uma tabela
        //rs = dao.mostraTabelaAcervo();
        //ResultSetMetaData metadados = null;
        /*try {
        metadados = rs.getMetaData();
        } catch (SQLException ex) {
        Logger.getLogger(InventarioUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        //GerenciadorRelatorios objGRD = new GerenciadorRelatorios(InventarioUI.this, false, TabelaRelatorio.getModeloTabela());
        //GerenciadorRelatorios objGRD = new GerenciadorRelatorios(InventarioUI.this, false, new TabelaRelatorio(rs, metadados));
        GerenciadorRelatorios objGRD = new GerenciadorRelatorios(InventarioUI.this, false, dao.mostraTabelaAcervo2());
        
        if ((comboRelat.getSelectedItem().equals("Itens não localizados no acervo"))){
            System.out.println("Verdadeiro");
            objGRD.mostraChecks(true);
        }else {
            System.out.println("Falso");
            objGRD.mostraChecks(false);
        }
        
        //Passa a referência desta classe
        objGRD.setRefInventarioUI(InventarioUI.this);
        objGRD.setVisible(true);
        
    }//GEN-LAST:event_botGerRelatActionPerformed

    public static String getNomeRelatorio(){
        return (String) comboRelat.getSelectedItem();
    }
    
    private void userBDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userBDKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            setFocusPswd();
        }
    }//GEN-LAST:event_userBDKeyPressed

    private void pswdBDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswdBDKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Acho que tem que ter um bloco try catch em algum canto aqui
            dao.login(userBD.getText(), pswdBD.getText());
            userBD.setText("");
            pswdBD.setText("");
            //requestFocus();
            //InventarioDAO.fazLogin(userBD.getText(), pswdBD.getText());
        }
    }//GEN-LAST:event_pswdBDKeyPressed

    private void comboRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRelatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRelatActionPerformed

    private void botDesfInsCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDesfInsCodActionPerformed
        //Chama o método de remoção da última linha do BD de DAO
        JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
        setFocusCodBar();
    }//GEN-LAST:event_botDesfInsCodActionPerformed

    private void botLimpCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpCodActionPerformed
        limpaTelaInsercao();
    }//GEN-LAST:event_botLimpCodActionPerformed

    private void botInsCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botInsCodKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.out.println("ENTER_BOTÃO INSERIR");
            insereDados();
        }
    }//GEN-LAST:event_botInsCodKeyPressed

    private void botInsCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInsCodActionPerformed
        insereDados();
    }//GEN-LAST:event_botInsCodActionPerformed

    private void vrfExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrfExemplarActionPerformed
        System.out.println("Botão clicado");

        /*Observacoes obs = new Observacoes();
        obs.setVisible(true);
        obs.setRefInventarioUI(this);*/
        Observacoes obsD = new Observacoes(InventarioUI.this, rootPaneCheckingEnabled);
        obsD.setRefInventarioUI(InventarioUI.this);
        obsD.setVisible(true);
    }//GEN-LAST:event_vrfExemplarActionPerformed

    private void codBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codBarKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER){
            setFocusBotaoInserir();
        }
    }//GEN-LAST:event_codBarKeyPressed

    private void codBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codBarActionPerformed

    private void pswdBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdBDActionPerformed
        
        
    }//GEN-LAST:event_pswdBDActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("Janela fechada!");
        dao.fechaConexao();
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Janela fechada!");
        dao.fechaConexao();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaAcervo;
    private javax.swing.JPanel abaAjuda;
    private javax.swing.JPanel abaInicio;
    private javax.swing.JPanel abaRelatorios;
    private javax.swing.JPanel abaSIABI;
    private javax.swing.JButton botCargAcervo;
    private javax.swing.JButton botCargSIABI;
    private javax.swing.JButton botDesfInsCod;
    private javax.swing.JButton botGerRelat;
    private javax.swing.JButton botInsCod;
    private javax.swing.JButton botLimpCod;
    private javax.swing.JButton botOk;
    private javax.swing.JButton botSelAcervo;
    private javax.swing.JButton botSelSIABI;
    private javax.swing.JTextField codBar;
    private static javax.swing.JComboBox<String> comboRelat;
    private javax.swing.JTextField endArqAcervo;
    private javax.swing.JTextField endArqSIABI;
    private javax.swing.JTabbedPane grupoAbas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel painelCargArqAcervo;
    private javax.swing.JPanel painelCargArqSIABI;
    private javax.swing.JPanel painelLeCodAcervo;
    private javax.swing.JTextField pswdBD;
    private javax.swing.JTable tabUltCod;
    private javax.swing.JTable tabUltIni;
    private javax.swing.JTextField userBD;
    private javax.swing.JRadioButton vrfExemplar;
    // End of variables declaration//GEN-END:variables
}
