/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.uepb.bsc7.www.UI;

import com.br.uepb.bsc7.www.persistence.InventarioDAO;
import java.awt.Component;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Diego
 */
public class PesquisaBD extends javax.swing.JDialog {

    /**
     * Creates new form PesquisaBD
     */
    InventarioDAO dao = null;
    
    public PesquisaBD(java.awt.Frame parent, boolean modal, InventarioDAO objDAO) {
        super(parent, modal);
        dao = objDAO;
        initComponents();
        travaTextFields(false, false, false);
        setVisible(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelPesq = new javax.swing.JPanel();
        radioSeq = new javax.swing.JRadioButton();
        radioCod = new javax.swing.JRadioButton();
        radioObs = new javax.swing.JRadioButton();
        textFieldSeq = new javax.swing.JTextField();
        textFieldCod = new javax.swing.JTextField();
        textFieldObs = new javax.swing.JTextField();
        botPesq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelPesq.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione o critério de pesquisa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        buttonGroup1.add(radioSeq);
        radioSeq.setText("Sequência:");
        radioSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSeqActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioCod);
        radioCod.setText("Código de barras:");
        radioCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCodActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioObs);
        radioObs.setText("Texto contido no campo \"Observações\":");
        radioObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioObsActionPerformed(evt);
            }
        });

        textFieldSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSeqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPesqLayout = new javax.swing.GroupLayout(painelPesq);
        painelPesq.setLayout(painelPesqLayout);
        painelPesqLayout.setHorizontalGroup(
            painelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioSeq)
                    .addComponent(radioCod)
                    .addComponent(radioObs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldObs, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelPesqLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textFieldCod, textFieldObs, textFieldSeq});

        painelPesqLayout.setVerticalGroup(
            painelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesqLayout.createSequentialGroup()
                .addGroup(painelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPesqLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(radioSeq))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPesqLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textFieldSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCod)
                    .addComponent(textFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioObs)
                    .addComponent(textFieldObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        botPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/uepb/bsc7/www/images/icon_pesquisar.png"))); // NOI18N
        botPesq.setText("Pesquisar");
        botPesq.setToolTipText("Insere o valor acima na tabela");
        botPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesqActionPerformed(evt);
            }
        });
        botPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botPesqKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botPesq)
                    .addComponent(painelPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(painelPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botPesq)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesqActionPerformed

        for (int i = 0; i < painelPesq.getComponentCount(); i++) {

            Component comp = painelPesq.getComponent(i);

            if (comp instanceof JRadioButton) {

                JRadioButton radio = (JRadioButton) comp;

                if (radio.isSelected()) {
                    System.out.println(radio.getText());
                    if (radio.getText().equals("Sequência:")) {
                        new TelaPesquisa(null, true, dao.pesquisaLinha(textFieldSeq.getText(), 1), dao);
                    } else {
                        if (radio.getText().equals("Código de barras:")) {
                            new TelaPesquisa(null, true, dao.pesquisaLinha(textFieldCod.getText(), 2), dao);
                        }
                        if (radio.getText().equals("Texto contido no campo \"Observações\":")) {
                            new TelaPesquisa(null, true, dao.pesquisaLinha(textFieldObs.getText(), 3), dao);
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_botPesqActionPerformed

    private void botPesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botPesqKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botPesqKeyPressed

    private void textFieldSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSeqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSeqActionPerformed

    private void travaTextFields(boolean a, boolean b, boolean c){
        textFieldSeq.setText("");
        textFieldCod.setText("");
        textFieldObs.setText("");
        
        textFieldSeq.setEnabled(a);
        textFieldCod.setEnabled(b);
        textFieldObs.setEnabled(c);
        
    }
    
    private void setFocusTextFieldCod() {
        textFieldCod.requestFocusInWindow();
    }
    
    private void setFocusTextFieldSeq() {
        textFieldSeq.requestFocusInWindow();
    }
    
    private void setFocusTextFieldObs() {
        textFieldObs.requestFocusInWindow();
    }
    
    private void radioCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCodActionPerformed
        travaTextFields(false, true, false);
        setFocusTextFieldCod();
    }//GEN-LAST:event_radioCodActionPerformed

    private void radioSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSeqActionPerformed
        travaTextFields(true, false, false);
        setFocusTextFieldSeq();
    }//GEN-LAST:event_radioSeqActionPerformed

    private void radioObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioObsActionPerformed
        travaTextFields(false, false, true);
        setFocusTextFieldObs();
    }//GEN-LAST:event_radioObsActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botPesq;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel painelPesq;
    private javax.swing.JRadioButton radioCod;
    private javax.swing.JRadioButton radioObs;
    private javax.swing.JRadioButton radioSeq;
    private javax.swing.JTextField textFieldCod;
    private javax.swing.JTextField textFieldObs;
    private javax.swing.JTextField textFieldSeq;
    // End of variables declaration//GEN-END:variables
}
